version: '3.8'

services:
  erms-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - erms-network

networks:
  erms-network:

    driver: bridge
