version: '3.8'

services:
  erms-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - erms-network

  erms-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - API__BaseUrl=http://erms-api:80
    depends_on:
      - erms-api
    networks:
      - erms-network

networks:
  erms-network:
    driver: bridge