// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERMS.DAL.Data;

public partial class User
{
    public long UserId { get; set; }

    public string Name { get; set; }

    public string FirstName { get; set; }

    public string Email { get; set; }
}